<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Microsoft.PowerShell.ScriptAnalyzer.Formatter.Core</AssemblyName>
    <RootNamespace>Microsoft.PowerShell.ScriptAnalyzer.Formatter</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management.Automation" />
  </ItemGroup>
</Project>
